<img src="https://api.nuget.org/v3-flatcontainer/numpy/3.7.1.10/icon" style="float: left; margin: 20px; height: 55px">

# NumPy & Linear Algebra

_Author: Alfred Zou_

---

* NumPy, or numerical python, is a popular python package for numerical calculations
* It introduces the nparray class that allows vectors and matrices to be stored and mathmatically operated on
* This allows for applications of linear algebra, which are extremely and heavily used for data scientists
* There are many applications for linear algebra, but they are not too clear to me at this moment
* One of the main uses is to solve multiple simultaneous equations at once

## Linear Algebra
---
* Linear algebra is the branch of mathematics concerning linear equations through vectors and matrices 
* [3B1B's geometric explanation of linear algebra is a great series](https://www.youtube.com/watch?v=fNk_zzaMoSs&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab)

### Vectors
* A vector is a collection of points
* It can also be perceived as either a arrow originating from the origin, the physics explaination

### $$\vec{v} = \left[ \begin{array}{c}
1 \\
3 \\
7 \\
\end{array} \right]$$

##### Vector Operations
* Vectors are usually denoted by **u**, **v** and **w** or a lowercase letter, with an arrow pointing right on top, $\vec{a}$. This is to distinguish them from the lowercase scalars
* Vectors can be added and subtracting
    * Mathematically, this is simply an elementwise operation. 

<img src="http://www.maths.usyd.edu.au/u/MOW/vectors/images/v0314x.gif" style="margin:20px;margin-left:auto;margin-right:auto;height:200px">

* Alternatively they can be scaled by a multiplying with a scalar
    * Mathematically, this is simply an elementwise operation. Geometrically, imagine a vector stretching by the factor of the scalar

<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS8Z8fRL2SOjwBz7QduNRPjqaxd8GV2wkGFo2-HQ8B_Qelr4uCq" style="margin:20px;margin-left:auto;margin-right:auto;height:250px;">


##### Dot Product
* Dot product of two vectors provides us some idea on if they orientate in the same direction:
    * positive: they orientate in the same direction
    * 0: they're perpendicular
    * negative: they orientate in opposite directions
* For a geometric explaination refer to the matrix multiplication section.
    * A 2D plane is squashed into a 1D line
* Although vector dot products are usually represented by two column vectors, its a good habit to visualise the first vector transposed
* This makes it more relatable to matrix multiplication, which will be explained further on
    
### $$\vec{v} = \left[ \begin{array}{c}
1 \\
3 \\
7
\end{array} \right], \vec{w} = \left[ \begin{array}{c}
1 \\
0 \\
1
\end{array} \right]$$

### $$\vec{v} \cdot \vec{w} = \left[ \begin{array}{c}
1 & 3 & 7
\end{array} \right] \left[ \begin{array}{c}
1 \\
0 \\
1
\end{array} \right]$$

### $$ \vec{v} \cdot \vec{w} = 1*1 + 3*0 + 7*1 = 8 $$

##### Cross Product
* I won't go too much in detail about cross product
* Cross product of two vectors is another vector, perpendicular to the initial two vectors
* The orientation of the cross product can be determined by the right hand rule
* The length of the cross product is equal to the determinant of the intial two vectors

<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRkmnGlK9LKL5sDBBoj3wHr9H9ty0XPkHYgPfLxEZJx3qML-PTZ" style="margin:20px;margin-left:auto;margin-right:auto;height:250px">

##### Matrix
* A matrix is a collection of points with at least two columns
* Essentially a matrix is just a one or more vectors. The operations we can perform on a vector can also be performed on a matrix
* Matrices are denoted by a capital letter such as A
* An m x n matrix is a rectangular array of numbers with m rows and n columns
* The elements are indexed by i,j. Where i represents the row and j the column

### $$A= \left[ \begin{array}{c}
a_{11} & a_{12} & ... & a_{1n}  \\
a_{21} & a_{22} & ... & a_{2n}  \\
... & ... & ... & ... \\
a_{m1} & a_{m2} & ... & a_{mn}
\end{array} \right]$$

##### Matrix Multiplication Graphical Explaination
* Matrix multiplication is often taught mathematically and with rote memorisation, leaving students confused
* There is actually a very intuitive graphical explaination that is often not taught
* [If you haven't tried out 3B1B's videos on matrix multiplication, I highly implore you to](https://www.youtube.com/watch?v=fNk_zzaMoSs&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab)
* [Coranac's explaination is amazing as well](https://www.coranac.com/documents/geomatrix/)
* To understand the graphical approach we first need to understand the concept of a basis

##### Basis
* For a 3D space, the cartesian co-ordinate system is made of the 3 bases: $\hat{i}, \hat{j}, \hat{k}$
* These bases are unit vectors, which means they have a length of 1
* These bases are also perpendicular to each other

<img src="https://mathinsight.org/media/applet/image/large/standard_unit_vectors_3d.png" style="margin:20px;margin-left:auto;margin-right:auto;height:200px">

##### Graphical Explaination TBC
* Image A is a random collection of points
* We can choose whatever co-ordinate system we like to represent these points
    * Image B-D shows a cartesian co-ordinate system at point A
    * Let's take this co-ordinate system
    
<img src="https://www.coranac.com/img/geomatrix/cosys-alt1.png" style="margin:20px;margin-left:auto;margin-right:auto;height:400px">

* Let's choose another co-ordinate system with different basis vectors
    
<img src="https://www.coranac.com/img/geomatrix/cosys-alt2.png" style="margin:20px;margin-left:auto;margin-right:auto;height:200px">

* Now we have the co-ordinates of the point P from the non cartesian co-ordinate system
* We can relate it back to the cartesian co-ordinate system by multiplying the matrix of 
* 

<img src="https://www.coranac.com/img/geomatrix/cosys-es.png" style="margin:20px;margin-left:auto;margin-right:auto;height:200px">
<img src="https://www.coranac.com/img/geomatrix/cosys-sine.png" style="margin:20px;margin-left:auto;margin-right:auto;height:200px">

##### Matrix Multiplication Mathematical Explaination
* Matrix multiplication from an mathematic standpoint is essentially multiple vector dot products
* Lets say we have matrix A with dimensions (m x n) and matrix B with dimensions (o x p)
    * To successfully carry out a matrix mulitiplication the number of columns for A must be the same as the number of rows for B, or n = o
    * This is required so multiple vector dot products can be applied
    * The resulting matrix will have the dimensions (m x p)
* AB != BA: matrix multiplication is not commutative, so order matters

<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRs82DjaoR599zTFd9CwH3g616quyOEq2J44Jv8mcP7D3aN8aBD" style="margin:20px;margin-left:auto;margin-right:auto;height:150px">

##### Determinant 
* The determinant can only be calculated for square matrices with m x m shape
* It is the parallelogram area bounded by two vectors
* It represents how any 2D area or 3D volume will scale if the matrix was 
* The determinant is also a check for linear independence:
    * If the determinant is 0, the column vectors for the matrix are linerally dependent

##### Rank
* Rank is the comparison between the determinant and the number of columns in the matrix
* It is the number of independent column vectors. This number represents the dimension of the span, the set of all possible output values
* If a column vector can be expressed by another column vectory, they are linearlly dependent. That means the span does not gain another dimension
* If the rank is equal to the number of columns, the matrix is said to be full rank

##### Special Matrices
* The identity matrix, I
    * IA = A
    
### $$ \left[ \begin{array}{c}
1 & 0 \\
0 & 1 
\end{array} \right] \cdot \left[ \begin{array}{c}
3 & 4 \\
5 & 6 
\end{array} \right] = \left[ \begin{array}{c}
(1 \cdot 3 + 0 \cdot 5) & (1 \cdot 4 + 0 \cdot 6) \\
(0 \cdot 3 + 1 \cdot 5) & (0 \cdot 4 + 1 \cdot 6) 
\end{array} \right] =
\left[ \begin{array}{c}
3 & 4 \\
5 & 6 
\end{array} \right]$$

* The inverse matrix, the inverse of A is A<sup>-1</sup>
    * A<sup>-1</sup>A = I 

##### Solving Multiple Linear Algebras TBC
* The general form is:
    * AX = y
    * A<sup>-1</sup>AX = A<sup>-1</sup>y
    * IX = A<sup>-1</sup>y
    * X = A<sup>-1</sup>y

### $$ ax_1 + dx_2 + gx_3 = y_1 $$
### $$ bx_1 + ex_2 + hx_3 = y_2 $$
### $$ cx_1 + fx_2 + ix_3 = y_3 $$

### $$AX = y$$

### $$$$

### $$\vec{i} = \left[ \begin{array}{c}
a \\
b \\
c
\end{array} \right], \vec{j} = \left[ \begin{array}{c}
d \\
e \\
f
\end{array} \right],\vec{k} = \left[ \begin{array}{c}
g \\
h \\
i
\end{array} \right]$$

### $$A= \left[ \begin{array}{c}
a & d & g  \\
b & e & h  \\
c & f & i
\end{array} \right],X = \left[ \begin{array}{c}
x_1 \\
x_2 \\
x_3
\end{array} \right]$$

##### Eigenvectors and Eigenvalues
* An eigenvector is a vector that when transformed, stretches by a factor known as the eigenvalue
    * $A\vec{v}=\lambda\vec{v}$
* I'm not too clear on the use about eigenvectors and eigenvalues, but I know they are important in speeding up simultaneous equations
* We can solve below to find the eigenvector and eigenvalue
* $A\vec{v}=\lambda\vec{v}$
* $A\vec{v}=\lambda I\vec{v}$
* $(A-\lambda I)\vec{v}=0, \vec{v}\neq0$

## Numpy
---

#### Vectors
---

##### Creation

In [14]:
# Creating a vector
import numpy as np
vector = np.array([1,2,3,4])
print(vector)

[1 2 3 4]


##### Dot product

In [20]:
# Vector multiplication
# Vectors need to be the same length
u = np.array([1,2,3,4])
v = np.array([2,3,4,5])
u.dot(v)

40

##### Vector Length

In [15]:
# Calculating the length of a vector or the vector norm
np.linalg.norm(np.array([3,4]))

5.0

##### Vector Array Creation

In [61]:
# arange() works similarly to range(), may give floating point error
# This is seen by calling the last value, where we expect to see 0.001
a = np.arange(-1., 0.001, 0.01)
a[-1]

8.881784197001252e-16

In [62]:
# The alternative is linspace, where number of samples is indicated
# This is preferred to reduce floats with large decimals
a = np.linspace(-1., 0.001, 1000)
a[-1]

0.001

### Matrixes
---

#### Matrices Creation

##### Supplying Lists

In [13]:
# np.array accepts rows then cols
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
matrix = np.array([[1,2],[3,4],[5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


##### Random

In [76]:
matrix = np.random.rand(3,4)
print(matrix)

[[0.22998154 0.38066297 0.28199135 0.34077443]
 [0.20467937 0.37259301 0.95480868 0.15035346]
 [0.53724267 0.20320423 0.3656962  0.22148118]]


In [77]:
matrix = np.random.randint(5,10,size=(3,4))
print(matrix)

[[6 6 6 8]
 [9 7 9 9]
 [8 5 9 6]]


In [76]:
matrix = np.random.rand(3,4)
print(matrix)

[[0.22998154 0.38066297 0.28199135 0.34077443]
 [0.20467937 0.37259301 0.95480868 0.15035346]
 [0.53724267 0.20320423 0.3656962  0.22148118]]


##### Zeros and Ones

In [97]:
matrix = np.zeros((3,4))
print(matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [98]:
matrix = np.ones((3,4))
print(matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


##### Normal Distribution

In [25]:
# 3D array based on normal distribution with mean = 0 and std = 1
matrix = np.random.normal(0, 1, (3,2,2))
print(matrix)

[[[-0.44398196 -0.43435128]
  [ 2.20593008  2.18678609]]

 [[ 1.0040539   0.3861864 ]
  [ 0.73736858  1.49073203]]

 [[-0.93583387  1.17582904]
  [-1.25388067 -0.6377515 ]]]


#### Matrices Other

##### Idexing

In [100]:
# Indexing
matrix = np.array([['0,0','0,1','0,2'],['1,0','1,1','1,2'],['2,0','2,1','2,2']])
print(matrix)
# Return the element for row 0 and column 1
matrix[0,1]

[['0,0' '0,1' '0,2']
 ['1,0' '1,1' '1,2']
 ['2,0' '2,1' '2,2']]


'0,1'

##### Multiplication

In [68]:
# Before multiplying matrices together, we need to make sure the number of columns in the first matrix matches the number of rows in the second matrix
A = np.array([[1,2],[3,4],[5,6]])
print(A.shape)
B = np.array([[1,2],[3,4]])
print(B.shape)
# 2 columns from the first matrix match the 2 rows from the second matrix, OK

# Our expected resulting matrix will be 3 rows and 2 columns
C = A.dot(B)
print(C)
print(C.shape)

# Alternatively
C = A@B
print(C)

(3, 2)
(2, 2)
[[ 7 10]
 [15 22]
 [23 34]]
(3, 2)
[[ 7 10]
 [15 22]
 [23 34]]


##### Matrix Properties

In [66]:
# ndim returns the number of dimensions for the matrix
A = np.array([[[1,3],[5,2]]])
A.ndim

3

In [91]:
# np.linalg.det() returs the determinant
A = np.array([[1,2,0],[0,1,1],[1,2,0]])
np.linalg.det(A)

0.0

##### Transpose

In [92]:
# transpose
A = np.array([[1,2,0],[0,1,1],[1,2,0]]).T
A

array([[1, 0, 1],
       [2, 1, 2],
       [0, 1, 0]])

##### Functions

In [108]:
# sum
A = np.array([[1,2,0],[0,1,1],[1,2,0]])
print(A)
# if we don't provide any arguments, its for the whole matrix
print(A.sum())
# down the rows
print(A.sum(axis=0))
# across the columns
print(A.sum(axis=1))
# Similarly for min(), max()

[[1 2 0]
 [0 1 1]
 [1 2 0]]
8
[2 5 1]
[3 2 3]


##### Random

In [65]:
# Setting a random seed
# If we keep running this cell, the arrays never change
np.random.seed(100)
print(np.random.randint(0,11,size=50))
print(np.random.randint(0,11,size=50))

[ 8  8  3  7  7  0 10  4  2  5  2  2  2  1  0  8  4 10  0  9  6  2  4  1
  5  3  4  4  3  7  1  1  7  7  0  2  9  9  3  2  5  8  1  0  7  6  2  0
  8  2]
[ 5 10  1  8 10  1  5  4  2  8  3  5  0  9 10  3  6  3  4 10  7  6  3  9
  0  4  4  5  7  6  6  2 10  4  2  7  1 10  6 10  6  0 10  7  2  3  5  4
  2  4]


In [63]:
# If we run this cell without the random.seed(), the arrays change
# This shows the random.seed() only works for the cell it is in and does not affect the whole workbook
print(np.random.randint(0,11,size=50))

[ 2  3  2  7  0  6  9  8 10  2  1  1  2  2  6  2  4  5  1  7  5  4  0  1
  5  9  0  1  0  4  3  2  7 10  6  3  7  2  7  8  5  1 10  9  6  0  9  9
  2  5]


##### Reshaping

In [33]:
array = np.array([1,2,3,4,5,6])

In [34]:
# Reshaping an array
array.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
# Using -1 tells numpy to figure it out
array.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
# Using -1 tells numpy to figure it out
array.reshape(2,-1).reshape(-1)

array([1, 2, 3, 4, 5, 6])

##### Matrix into a vector (or flattening)

In [55]:
matrix = np.array([[1,2,3],[4,5,6]])
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
# we can turn it back into a vector
print(matrix.reshape(-1))
print(matrix.reshape(-1).shape)

[1 2 3 4 5 6]
(6,)


##### Raveling (or flattening)
* It's the same as calling `.reshape(-1)`

In [62]:
matrix.ravel()

array([1, 2, 3, 4, 5, 6])

##### Concatenation with `.concatenate`

In [76]:
matrix1 = np.array([[1,2],[4,5]])
matrix2 = np.array([[7,8]])

In [79]:
np.concatenate((matrix1,matrix2),axis=0)

array([[1, 2],
       [4, 5],
       [7, 8]])

In [78]:
np.concatenate((matrix1,matrix2.T),axis=1)

array([[1, 2, 7],
       [4, 5, 8]])

#### Descriptive Statistics

In [10]:
np.random.seed(101)
a = list(np.random.randint(0,11,size=20))
print('list: ',a)
print('sorted list: ',sorted(a))
print('sum: ',np.sum(a))
print('length: ',len(a))
print('mean: ',np.mean(a))
print('median: ',np.median(a))
print('range: ',np.ptp(a))
print('variance: ',np.var(a))
print('standard deviation: ',np.std(a))

list:  [1, 6, 7, 9, 8, 4, 8, 5, 0, 5, 8, 1, 3, 10, 8, 3, 3, 2, 8, 9]
sorted list:  [0, 1, 1, 2, 3, 3, 3, 4, 5, 5, 6, 7, 8, 8, 8, 8, 8, 9, 9, 10]
sum:  108
length:  20
mean:  5.4
median:  5.5
range:  10
variance:  9.139999999999999
standard deviation:  3.0232432915661946


In [17]:
# Unfortunately there is no mode provided by np
# Instead we use SciPy
import scipy.stats as stats
print(stats.mode(a))
print('The mode is:',stats.mode(a)[0],', which appears',stats.mode(a)[1],'times')

ModeResult(mode=array([8]), count=array([5]))
The mode is: [8] , which appears [5] times
